project:
  type: book
  output-dir: docs

book:
  title: "Tidy Data Analysis"


  chapters:
    - index.qmd
    - what-is-tidyverse.qmd

format:
  html:
    callout-appearance: simple
    theme: cosmo