project:
    type: book
    output-dir: docs

book:
    title: "Tidy Data Analysis"

    chapters:
        - index.qmd
        - what-is-tidyverse.qmd

format:
    html:
        theme: cosmo
        highlight-style: atom-one
